### ISSUE TITLE
Blacklisting worlds

### ISSUE THREAD

**Issue by NEINtje** [pmdevita/StayPut#36]
So I am trying to blacklist my spawn world because I am trying to make it so when the command /mvtp spawn is executed it will teleport them to a certain block instead of their last location. However when I add the world "spawn" to my blacklist it still doesn't put the player back at the world spawn when executing /mvtp spawn. Anyone know a fix? Ive added an image of how I have it set up.
![image_2024-01-01_155525649](https://github.com/pmdevita/StayPut/assets/91952040/cb7ac9e4-a109-4b1e-bc19-8fafda01bb07)

**Comment by tumblinpanda** [comment]
Bump. Same here
![Capture32](https://github.com/pmdevita/StayPut/assets/168128031/13f5b3f1-e9ef-4a78-8f5d-ea8aa80911b2)

**Comment by tumblinpanda** [comment]
> So I am trying to blacklist my spawn world because I am trying to make it so when the command /mvtp spawn is executed it will teleport them to a certain block instead of their last location. However when I add the world "spawn" to my blacklist it still doesn't put the player back at the world spawn when executing /mvtp spawn. Anyone know a fix? Ive added an image of how I have it set up. ![image_2024-01-01_155525649](https://private-user-images.githubusercontent.com/91952040/293592660-cb7ac9e4-a109-4b1e-bc19-8fafda01bb07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwODk5MjIsIm5iZiI6MTcxNDA4OTYyMiwicGF0aCI6Ii85MTk1MjA0MC8yOTM1OTI2NjAtY2I3YWM5ZTQtYTEwOS00YjFlLWJjMTktOGZhZmRhMDFiYjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAwMDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOWIxZDA0ZDM4Yjg3YzQzY2E5YmNjMWU2M2Q1ODJmOTZlYzZkNjVjYWFmZDM0MmE1MzNjYjBlNGM1MjI5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HgckR-u-OVyVFXzAZ_4I8Nie-z90J5i3aZil4FjfLzA)

Hey so i found the fix you are looking for! I ran into the same issue and then realised i was being silly you have to add the " around the world names! Also restart the server as reloading the blacklist using '/stayput reload' was not working for me. This should definitely fix your issue!

Example Image
![image](https://github.com/pmdevita/StayPut/assets/168128031/f660d3a2-4e60-4f63-aa76-4d9b765e676d)

**Comment by deko0** [comment]
hello! unfortunately, if i add my world named Spawn to the list, it still teleports me back to my last position in the spawn world.
This is how i have it setup:

![Image](https://github.com/user-attachments/assets/b5c9c4d3-0eb3-4cbd-ba10-9e8b561ce81f)

Also, debug mode does not seem to do anything for me.

**Comment by pmdevita** [comment]
Hmm... thinking outside the box a bit, if turning on debug mode doesn't make it print anything extra to the console and adding a world doesn't do anything, maybe there's something wrong with the config file? Is it in the StayPut folder in your plugins folder?

**Comment by deko0** [comment]
> Hmm... thinking outside the box a bit, if turning on debug mode doesn't make it print anything extra to the console and adding a world doesn't do anything, maybe there's something wrong with the config file? Is it in the StayPut folder in your plugins folder? Can you upload your config here?

sure. more info: I have created the world with Multiverse, and i have made sure it's called Spawn. 
Github won't let me upload the YML file so I'll just paste it here:
Also yes, it is in the plugins folder in the stayput folder. The server is in Purpur 1.21.4.
 
```yml
# Database configuration
database:
    # Type: sqlite (default), mysql, or mariadb
    type: "sqlite"
    # If you are using sqlite, you can configure the filename here (default: database.db)
    filename: "database.db"
    # If you are using MySQL/MariaDB, provide connection info here
    host: "localhost"
    port: 3306
    database: "database"
    username: "username"
    password: "password"

# Blacklisted worlds, which worlds should be excluded from the teleport actions?
# Example layout
 blacklisted-worlds:
  - "spawn"
# Want to debug and see why certain actions are (not) executed? Set this to true. Default: false
debug: true
```
